#ifndef _WBXML_H_
#define _WBXML_H_

#include <string>

#include "utils/filereader/filereader.h"

#pragma pack(push,1)

struct SBit {
	unsigned int m_uiBit : 1;
};

typedef SBit bit;
typedef unsigned char byte;
typedef unsigned char u_int8;

struct STokenId {
	u_int8 m_ui8CodePage;
	std::string m_strType;
	u_int8 m_ui8Token;
};

struct STokenData {
	std::string m_strName;
	std::string m_strValue;
};

struct SMBUI32 {
	union {
		unsigned char m_uiValue;
		struct {
			unsigned char m_b06 : 7;
			unsigned char m_bIndicator : 1; 
		};
	};
};

typedef SMBUI32 mb_u_int32;

struct SWBXMLToken {
	union {
		u_int8 m_ui8Value;
		struct {
			u_int8 m_uiToken : 6;
			u_int8 m_bContent : 1;
			u_int8 m_bAttr : 1;
		};
	};
};

struct STokenDescr {
	u_int8 m_ui8CodePage;
	std::string m_strType;
	SWBXMLToken m_soToken;
	std::string m_strTokenName;
	std::string m_strTokenValue;
};

static STokenDescr g_msoTokenDescr[] {
	/* WAP-192-WBXML-20010725-a */
	{ -1, "element", { 0x00 }, "SWITCH_PAGE", ""		/* Change the code page for the current token state. Followed by a single u_int8 indicating the new code page number */ },
	{ -1, "element", { 0x01 }, "END", ""		/* Indicates the end of an attribute list or the end of an element */ },
	{ -1, "element", { 0x02 }, "ENTITY", ""		/* A character entity. Followed by a mb_u_int32 encoding the character entity number */ },
	{ -1, "element", { 0x03 }, "STR_I", ""		/* Inline string. Followed by a termstr */ },
	{ -1, "element", { 0x04 }, "LITERAL", ""		/* An unknown attribute name, or unknown tag posessing no attributes or content.Followed by a mb_u_int32 that encodes an offset into the string table*/ },
	{ -1, "element", { 0x40 }, "EXT_I_0", ""	/* Inline string document-type-specific extension token. Token is followed by a termstr */ },
	{ -1, "element", { 0x41 }, "EXT_I_1", ""	/* Inline string document-type-specific extension token. Token is followed by a termstr */ },
	{ -1, "element", { 0x42 }, "EXT_I_2", ""	/* Inline string document-type-specific extension token. Token is followed by a termstr */ },
	{ -1, "element", { 0x43 }, "PI", ""	/* Processing instruction */ },
	{ -1, "element", { 0x44 }, "LITERAL_C", ""	/* An unknown tag posessing content but no attributes */ },
	{ -1, "element", { 0x80 }, "EXT_T_0", ""	/* Inline integer document-type-specific extension token. Token is followed by a mb_u_int32 */ },
	{ -1, "element", { 0x81 }, "EXT_T_1", ""	/* Inline integer document-type-specific extension token. Token is followed by a mb_u_int32 */ },
	{ -1, "element", { 0x82 }, "EXT_T_2", ""	/* Inline integer document-type-specific extension token. Token is followed by a mb_u_int32 */ },
	{ -1, "element", { 0x83 }, "STR_T", ""	/* String table reference. Followed by a mb_u_int32 encoding a byte offset from the beginning of the string table */ },
	{ -1, "element", { 0x84 }, "LITERAL_A", ""	/* An unknown tag posessing attributes but no content */ },
	{ -1, "element", { 0xC0 }, "EXT_0", ""	/* Single -byte document-type-specific extension token */ },
	{ -1, "element", { 0xC1 }, "EXT_1", ""	/* Single -byte document-type-specific extension token */ },
	{ -1, "element", { 0xC2 }, "EXT_2", ""	/* Single -byte document-type-specific extension token */ },
	{ -1, "element", { 0xC3 }, "OPAQUE", ""	/* Opaque document-type-specific data */ },
	{ -1, "element", { 0xC4 }, "LITERAL_AC", ""	/* An unknown tag posessing both attributes and content */ }
	/* OMA-WAP-TS-ProvCont-V1_1-20090728-A */ ,
	{ 0, "element", { 0x5 }, "wap-provisioningdoc", "" },
	{ 0, "attribute", { 0x45 }, "version", "" },
	{ 0, "attribute", { 0x46 }, "version", "1.0" },
	{ 0, "element", { 0x6 }, "characteristic", "" },
	{ 0, "attribute", { 0x50 }, "type", "" },
	{ 0, "attribute", { 0x51 }, "type", "PXLOGICAL" },
	{ 0, "attribute", { 0x52 }, "type", "PXPHYSICAL" },
	{ 0, "attribute", { 0x53 }, "type", "PORT" },
	{ 0, "attribute", { 0x54 }, "type", "VALIDITY" },
	{ 0, "attribute", { 0x55 }, "type", "NAPDEF" },
	{ 0, "attribute", { 0x56 }, "type", "BOOTSTRAP" },
	{ 0, "attribute", { 0x57 }, "type", "VENDORCONFIG" },
	{ 0, "attribute", { 0x58 }, "type", "CLIENTIDENTITY" },
	{ 0, "attribute", { 0x59 }, "type", "PXAUTHINFO" },
	{ 0, "attribute", { 0x5A }, "type", "NAPAUTHINFO" },
	{ 0, "attribute", { 0x5B }, "type", "ACCESS" },
	{ 1, "element", { 0x6 }, "characteristic", "" },
	{ 1, "attribute", { 0x50 }, "type", "" },
	{ 1, "attribute", { 0x53 }, "type", "PORT" },
	{ 1, "attribute", { 0x58 }, "type", "CLIENTIDENTITY" },
	{ 1, "attribute", { 0x55 }, "type", "APPLICATION" },
	{ 1, "attribute", { 0x56 }, "type", "APPADDR" },
	{ 1, "attribute", { 0x57 }, "type", "APPAUTH" },
	{ 1, "attribute", { 0x59 }, "type", "RESOURCE" },
	{ 0, "element", { 0x7 }, "parm", "" },
	{ 0, "attribute", { 0x5 }, "name", "" },
	{ 0, "attribute", { 0x6 }, "value", "" },
	{ 0, "attribute", { 0x7 }, "name", "NAME" },
	{ 0, "attribute", { 0x8 }, "name", "NAP-ADDRESS" },
	{ 0, "attribute", { 0x9 }, "name", "NAP-ADDRTYPE" },
	{ 0, "attribute", { 0xA }, "name", "CALLTYPE" },
	{ 0, "attribute", { 0xB }, "name", "VALIDUNTIL" },
	{ 0, "attribute", { 0xC }, "name", "AUTHTYPE" },
	{ 0, "attribute", { 0xD }, "name", "AUTHNAME" },
	{ 0, "attribute", { 0xE }, "name", "AUTHSECRET" },
	{ 0, "attribute", { 0xF }, "name", "LINGER" },
	{ 0, "attribute", { 0x10 }, "name", "BEARER" },
	{ 0, "attribute", { 0x11 }, "name", "NAPID" },
	{ 0, "attribute", { 0x12 }, "name", "COUNTRY" },
	{ 0, "attribute", { 0x13 }, "name", "NETWORK" },
	{ 0, "attribute", { 0x14 }, "name", "INTERNET" },
	{ 0, "attribute", { 0x15 }, "name", "PROXY-ID" },
	{ 0, "attribute", { 0x16 }, "name", "PROXY-PROVIDER-ID" },
	{ 0, "attribute", { 0x17 }, "name", "DOMAIN" },
	{ 0, "attribute", { 0x18 }, "name", "PROVURL" },
	{ 0, "attribute", { 0x19 }, "name", "PXAUTH-TYPE" },
	{ 0, "attribute", { 0x1A }, "name", "PXAUTH-ID" },
	{ 0, "attribute", { 0x1B }, "name", "PXAUTH-PW" },
	{ 0, "attribute", { 0x1C }, "name", "STARTPAGE" },
	{ 0, "attribute", { 0x1D }, "name", "BASAUTH-ID" },
	{ 0, "attribute", { 0x1E }, "name", "BASAUTH-PW" },
	{ 0, "attribute", { 0x1F }, "name", "PUSHENABLED" },
	{ 0, "attribute", { 0x20 }, "name", "PXADDR" },
	{ 0, "attribute", { 0x21 }, "name", "PXADDRTYPE" },
	{ 0, "attribute", { 0x22 }, "name", "TO-NAPID" },
	{ 0, "attribute", { 0x23 }, "name", "PORTNBR" },
	{ 0, "attribute", { 0x24 }, "name", "SERVICE" },
	{ 0, "attribute", { 0x25 }, "name", "LINKSPEED" },
	{ 0, "attribute", { 0x26 }, "name", "DNLINKSPEED" },
	{ 0, "attribute", { 0x27 }, "name", "LOCAL-ADDR" },
	{ 0, "attribute", { 0x28 }, "name", "LOCAL-ADDRTYPE" },
	{ 0, "attribute", { 0x29 }, "name", "CONTEXT-ALLOW" },
	{ 0, "attribute", { 0x2A }, "name", "TRUST" },
	{ 0, "attribute", { 0x2B }, "name", "MASTER" },
	{ 0, "attribute", { 0x2C }, "name", "SID" },
	{ 0, "attribute", { 0x2D }, "name", "SOC" },
	{ 0, "attribute", { 0x2E }, "name", "WSP-VERSION" },
	{ 0, "attribute", { 0x2F }, "name", "PHYSICAL-PROXY-ID" },
	{ 0, "attribute", { 0x30 }, "name", "CLIENT-ID" },
	{ 0, "attribute", { 0x31 }, "name", "DELIVERY-ERR-SDU" },
	{ 0, "attribute", { 0x32 }, "name", "DELIVERY-ORDER" },
	{ 0, "attribute", { 0x33 }, "name", "TRAFFIC-CLASS" },
	{ 0, "attribute", { 0x34 }, "name", "MAX-SDU-SIZE" },
	{ 0, "attribute", { 0x35 }, "name", "MAX-BITRATE-UPLINK" },
	{ 0, "attribute", { 0x36 }, "name", "MAX-BITRATE-DNLINK" },
	{ 0, "attribute", { 0x37 }, "name", "RESIDUAL-BER" },
	{ 0, "attribute", { 0x38 }, "name", "SDU-ERROR-RATIO" },
	{ 0, "attribute", { 0x39 }, "name", "TRAFFIC-HANDL-PRIO" },
	{ 0, "attribute", { 0x3A }, "name", "TRANSFER-DELAY" },
	{ 0, "attribute", { 0x3B }, "name", "GUARANTEED-BITRATE-UPLINK" },
	{ 0, "attribute", { 0x3C }, "name", "GUARANTEED-BITRATE-DNLINK" },
	{ 0, "attribute", { 0x3D }, "name", "PXADDR-FQDN" },
	{ 0, "attribute", { 0x3E }, "name", "PROXY-PW" },
	{ 0, "attribute", { 0x3F }, "name", "PPGAUTH-TYPE" },
	{ 0, "attribute", { 0x47 }, "name", "PULLENABLED" },
	{ 0, "attribute", { 0x48 }, "name", "DNS-ADDR" },
	{ 0, "attribute", { 0x49 }, "name", "MAX-NUM-RETRY" },
	{ 0, "attribute", { 0x4A }, "name", "FIRST-RETRY-TIMEOUT" },
	{ 0, "attribute", { 0x4B }, "name", "REREG-THRESHOLD" },
	{ 0, "attribute", { 0x4C }, "name", "T-BIT" },
	{ 0, "attribute", { 0x4E }, "name", "AUTH-ENTITY" },
	{ 0, "attribute", { 0x4F }, "name", "SPI" },
	{ 1, "element", { 0x7 }, "parm", "" },
	{ 1, "attribute", { 0x5 }, "name", "" },
	{ 1, "attribute", { 0x6 }, "value", "" },
	{ 1, "attribute", { 0x7 }, "name", "NAME" },
	{ 1, "attribute", { 0x14 }, "name", "INTERNET" },
	{ 1, "attribute", { 0x1C }, "name", "STARTPAGE" },
	{ 1, "attribute", { 0x22 }, "name", "TO-NAPID" },
	{ 1, "attribute", { 0x23 }, "name", "PORTNBR" },
	{ 1, "attribute", { 0x24 }, "name", "SERVICE" },
	{ 1, "attribute", { 0x2E }, "name", "AACCEPT" },
	{ 1, "attribute", { 0x2F }, "name", "AAUTHDATA" },
	{ 1, "attribute", { 0x30 }, "name", "AAUTHLEVEL" },
	{ 1, "attribute", { 0x31 }, "name", "AAUTHNAME" },
	{ 1, "attribute", { 0x32 }, "name", "AAUTHSECRET" },
	{ 1, "attribute", { 0x33 }, "name", "AAUTHTYPE" },
	{ 1, "attribute", { 0x34 }, "name", "ADDR" },
	{ 1, "attribute", { 0x35 }, "name", "ADDRTYPE" },
	{ 1, "attribute", { 0x36 }, "name", "APPID" },
	{ 1, "attribute", { 0x37 }, "name", "APROTOCOL" },
	{ 1, "attribute", { 0x38 }, "name", "PROVIDER-ID" },
	{ 1, "attribute", { 0x39 }, "name", "TO-PROXY" },
	{ 1, "attribute", { 0x3A }, "name", "URI" },
	{ 1, "attribute", { 0x3B }, "name", "RULE" },
	{ 0, "value", { 0x85 }, "IPV4", "" },
	{ 0, "value", { 0x86 }, "IPV6", "" },
	{ 0, "value", { 0x87 }, "E164", "" },
	{ 0, "value", { 0x88 }, "ALPHA", "" },
	{ 0, "value", { 0x89 }, "APN", "" },
	{ 0, "value", { 0x8A }, "SCODE", "" },
	{ 0, "value", { 0x8B }, "TETRA-ITSI", "" },
	{ 0, "value", { 0x8C }, "MAN", "" },
	{ 1, "value", { 0x86 }, "IPV6", "" },
	{ 1, "value", { 0x87 }, "E164", "" },
	{ 1, "value", { 0x88 }, "ALPHA", "" },
	{ 1, "value", { 0x8D }, "APPSRV", "" },
	{ 1, "value", { 0x8E }, "OBEX", "" },
	{ 0, "value", { 0x90 }, "ANALOG-MODEM", "" },
	{ 0, "value", { 0x91 }, "V.120", "" },
	{ 0, "value", { 0x92 }, "V.110", "" },
	{ 0, "value", { 0x93 }, "X.31", "" },
	{ 0, "value", { 0x94 }, "BIT-TRANSPARENT", "" },
	{ 0, "value", { 0x95 }, "DIRECT-ASYNCHRONOUS-DATA-SERVICE", "" },
	{ 0, "value", { 0x9A }, "PAP", "" },
	{ 0, "value", { 0x9B }, "CHAP", "" },
	{ 0, "value", { 0x9C }, "HTTP-BASIC", "" },
	{ 0, "value", { 0x9D }, "HTTP-DIGEST", "" },
	{ 0, "value", { 0x9E }, "WTLS-SS", "" },
	{ 0, "value", { 0x9F }, "MD5", "" },
	{ 0, "value", { 0x9A }, "PAP", "" },
	{ 0, "value", { 0x9B }, "CHAP", "" },
	{ 0, "value", { 0x9C }, "HTTP-BASIC", "" },
	{ 0, "value", { 0x9D }, "HTTP-DIGEST", "" },
	{ 0, "value", { 0x9E }, "WTLS-SS", "" },
	{ 0, "value", { 0x9F }, "MD5", "" },
	{ 0, "value", { 0xA2 }, "GSM-USSD", "" },
	{ 0, "value", { 0xA3 }, "GSM-SMS", "" },
	{ 0, "value", { 0xA4 }, "ANSI-136-GUTS", "" },
	{ 0, "value", { 0xA5 }, "IS-95-CDMA-SMS", "" },
	{ 0, "value", { 0xA6 }, "IS-95-CDMA-CSD", "" },
	{ 0, "value", { 0xA7 }, "IS-95-CDMA-PACKET", "" },
	{ 0, "value", { 0xA8 }, "ANSI-136-CSD", "" },
	{ 0, "value", { 0xA9 }, "ANSI-136-GPRS", "" },
	{ 0, "value", { 0xAA }, "GSM-CSD", "" },
	{ 0, "value", { 0xAB }, "GSM-GPRS", "" },
	{ 0, "value", { 0xAC }, "AMPS-CDPD", "" },
	{ 0, "value", { 0xAD }, "PDC-CSD", "" },
	{ 0, "value", { 0xAE }, "PDC-PACKET", "" },
	{ 0, "value", { 0xAF }, "IDEN-SMS", "" },
	{ 0, "value", { 0xB0 }, "IDEN-CSD", "" },
	{ 0, "value", { 0xB1 }, "IDEN-PACKET", "" },
	{ 0, "value", { 0xB2 }, "FLEX/REFLEX", "" },
	{ 0, "value", { 0xB3 }, "PHS-SMS", "" },
	{ 0, "value", { 0xB4 }, "PHS-CSD", "" },
	{ 0, "value", { 0xB5 }, "TETRA-SDS", "" },
	{ 0, "value", { 0xB6 }, "TETRA-PACKET", "" },
	{ 0, "value", { 0xB7 }, "ANSI-136-GHOST", "" },
	{ 0, "value", { 0xB8 }, "MOBITEX-MPAK", "" },
	{ 0, "value", { 0xB9 }, "CDMA2000-1X-SIMPLE-IP", "" },
	{ 0, "value", { 0xBA }, "CDMA2000-1X-MOBILE-IP", "" },
	{ 0, "value", { 0xC5 }, "AUTOBAUDING", "" },
	{ 0, "value", { 0xCA }, "CL-WSP", "" },
	{ 0, "value", { 0xCB }, "CO-WSP", "" },
	{ 0, "value", { 0xCC }, "CL-SEC-WSP", "" },
	{ 0, "value", { 0xCD }, "CO-SEC-WSP", "" },
	{ 0, "value", { 0xCE }, "CL-SEC-WTA", "" },
	{ 0, "value", { 0xCF }, "CO-SEC-WTA", "" },
	{ 0, "value", { 0xD0 }, "OTA-HTTP-TO", "" },
	{ 0, "value", { 0xD1 }, "OTA-HTTP-TLS-TO", "" },
	{ 0, "value", { 0xD2 }, "OTA-HTTP-PO", "" },
	{ 0, "value", { 0xD3 }, "OTA-HTTP-TLS-PO", "" },
	{ 1, "value", { 0x90 }, ", (comma character)", "" },
	{ 1, "value", { 0x91 }, "HTTP-", "" },
	{ 1, "value", { 0x92 }, "BASIC", "" },
	{ 1, "value", { 0x93 }, "DIGEST", "" },
	{ 0, "value", { 0xE0 }, "AAA", "" },
	{ 0, "value", { 0xE1 }, "HA", "" }
	/* MSDN */,
	{ 200, "element", { 0x20 }, "characteristic-query", "" },
	{ 200, "element", { 0x21 }, "parm-query", "" },
	{ 200, "element", { 0x22 }, "nocharacteristic", "" },
	{ 200, "element", { 0x23 }, "noparm", "" },
	{ 200, "element", { 0x24 }, "characteristic-error", "" },
	{ 200, "element", { 0x25 }, "parm-error", "" },
	{ 200, "element", { 0x26 }, "characteristic-query-error", "" },
	{ 200, "element", { 0x27 }, "parm-query-error", "" },
	{ 200, "element", { 0x28 }, "nocharacteristic-error", "" },
	{ 200, "element", { 0x29 }, "noparm-error", "" },

	{ 201, "value", { 0x85 }, "HKCU\\", "" },
	{ 201, "value", { 0x86 }, "HKLM\\", "" },
	{ 201, "value", { 0x87 }, "HKCR\\", "" },
	{ 201, "value", { 0x88 }, "ControlPanel\\", "" },
	{ 201, "value", { 0x89 }, "Inbox\\", "" },
	{ 201, "value", { 0x8A }, "Software\\", "" },
	{ 201, "value", { 0x8B }, "Microsoft\\", "" },
	{ 201, "value", { 0x8C }, "Windows", "" },
	{ 201, "value", { 0x8D }, "Phone", "" },
	{ 201, "value", { 0x8E }, "AirSync\\", "" },
	{ 201, "value", { 0x8F }, "Settings", "" },
	{ 201, "value", { 0x90 }, "MessengerService\\", "" },
	{ 201, "value", { 0x91 }, "Default", "" },
	{ 201, "value", { 0x92 }, "Timeout", "" },
	{ 201, "value", { 0x93 }, "Security", "" },
	{ 201, "value", { 0x94 }, "Sound", "" },
	{ 201, "value", { 0x95 }, "Sounds", "" },
	{ 201, "value", { 0x96 }, "Policies", "" },
	{ 201, "value", { 0x97 }, "Policy", "" },

	{ 200, "attribute", { 0x60 }, "datatype", "" },
	{ 200, "attribute", { 0x61 }, "datatype", "string" },
	{ 200, "attribute", { 0x62 }, "datatype", "float" },
	{ 200, "attribute", { 0x63 }, "datatype", "date" },
	{ 200, "attribute", { 0x64 }, "datatype", "time" },
	{ 200, "attribute", { 0x65 }, "datatype", "boolean" },
	{ 200, "attribute", { 0x66 }, "datatype", "binary" },
	{ 200, "attribute", { 0x67 }, "datatype", "multiplestring" },
	{ 200, "attribute", { 0x68 }, "datatype", "integer" },
	{ 200, "attribute", { 0x69 }, "maxvalue", "" },
	{ 200, "attribute", { 0x6A }, "minvalue", "" },
	{ 200, "attribute", { 0x6B }, "maxlength", "" },
	{ 200, "attribute", { 0x6C }, "options", "" },
	{ 200, "attribute", { 0x6D }, "multiple", "" },
	{ 200, "attribute", { 0x6E }, "semantic-type", "" },
	{ 200, "attribute", { 0x6F }, "rw-access", "" },
	{ 200, "attribute", { 0x70 }, "nooverwrite", "" },
	{ 200, "attribute", { 0x71 }, "access-role", "" },
	{ 200, "attribute", { 0x72 }, "label", "" },
	{ 200, "attribute", { 0x73 }, "desc", "" },
	{ 200, "attribute", { 0x74 }, "recursive", "" },
	{ 200, "attribute", { 0x75 }, "code", "" },

	{ 201, "attribute", { 0x5 }, "type", "SecurityPolicy" },
	{ 201, "attribute", { 0x6 }, "type", "LoaderRevocation" },
	{ 201, "attribute", { 0x7 }, "type", "Registry" },
	{ 201, "attribute", { 0x10 }, "type", "CM_ProxyEntries" },
	{ 201, "attribute", { 0x11 }, "type", "CM_PPPEntries" },
	{ 201, "attribute", { 0x12 }, "type", "CM_VPNEntries" },
	{ 201, "attribute", { 0x13 }, "type", "CM_Planner" },
	{ 201, "attribute", { 0x14 }, "type", "CM_Networks" },
	{ 201, "attribute", { 0x15 }, "type", "CM_Mappings" },
	{ 201, "attribute", { 0x16 }, "type", "CM_GPRSEntries" },
	{ 201, "attribute", { 0x17 }, "type", "DevSpecificCellular" },
	{ 201, "attribute", { 0x18 }, "type", "PreferredConnections" },
	{ 201, "attribute", { 0x20 }, "name", "Pattern" },
	{ 201, "attribute", { 0x21 }, "name", "Network" },
	{ 201, "attribute", { 0x22 }, "name", "CoeffLatency" },
	{ 201, "attribute", { 0x23 }, "name", "CoeffCost" },
	{ 201, "attribute", { 0x24 }, "name", "CoeffBandwidth" },
	{ 201, "attribute", { 0x25 }, "name", "CacheTime" },
	{ 201, "attribute", { 0x26 }, "name", "RetryCount" },
	{ 201, "attribute", { 0x27 }, "name", "SrcId" },
	{ 201, "attribute", { 0x28 }, "name", "DestId" },
	{ 201, "attribute", { 0x29 }, "name", "Proxy" },
	{ 201, "attribute", { 0x2A }, "name", "UserName" },
	{ 201, "attribute", { 0x2B }, "name", "Password" },
	{ 201, "attribute", { 0x2C }, "name", "Type" },
	{ 201, "attribute", { 0x2D }, "name", "Override" },
	{ 201, "attribute", { 0x2E }, "name", "Enabled" },
	{ 201, "attribute", { 0x2F }, "name", "RequirePW" },
	{ 201, "attribute", { 0x30 }, "name", "DialAsLocalCall" },
	{ 201, "attribute", { 0x31 }, "name", "AltDnsAddr" },
	{ 201, "attribute", { 0x32 }, "name", "AltWinsAddr" },
	{ 201, "attribute", { 0x33 }, "name", "DeviceName" },
	{ 201, "attribute", { 0x34 }, "name", "DeviceType" },
	{ 201, "attribute", { 0x35 }, "name", "DnsAddr" },
	{ 201, "attribute", { 0x36 }, "name", "Framing" },
	{ 201, "attribute", { 0x37 }, "name", "FrameSize" },
	{ 201, "attribute", { 0x38 }, "name", "IpAddr" },
	{ 201, "attribute", { 0x39 }, "name", "Script" },
	{ 201, "attribute", { 0x3A }, "name", "WinsAddr" },
	{ 201, "attribute", { 0x3B }, "name", "DeviceSpecificRAW" },
	{ 201, "attribute", { 0x3C }, "name", "SpecificNameServers" },
	{ 201, "attribute", { 0x3D }, "name", "IpHeaderCompression" },
	{ 201, "attribute", { 0x3E }, "name", "SwCompression" },
	{ 201, "attribute", { 0x3F }, "name", "UserCountryAndAreaCodes" },
	{ 201, "attribute", { 0x45 }, "name", "RequireEncryptedPw" },
	{ 201, "attribute", { 0x46 }, "name", "RequireMSEncryptedPw" },
	{ 201, "attribute", { 0x47 }, "name", "RequireDataEncryption" },
	{ 201, "attribute", { 0x48 }, "name", "Domain" },
	{ 201, "attribute", { 0x49 }, "name", "Phone" },
	{ 201, "attribute", { 0x4A }, "name", "AreaCode" },
	{ 201, "attribute", { 0x4B }, "name", "CountryCode" },
	{ 201, "attribute", { 0x4C }, "name", "BearerInfoValid" },
	{ 201, "attribute", { 0x4D }, "name", "BearerInfoSpeed" },
	{ 201, "attribute", { 0x4E }, "name", "BearerInfoService" },
	{ 201, "attribute", { 0x4F }, "name", "BearerInfoConnectionelement," },
	{ 201, "attribute", { 0x50 }, "name", "GPRSInfoValid" },
	{ 201, "attribute", { 0x51 }, "name", "GPRSInfoQOSSettingsValid" },
	{ 201, "attribute", { 0x52 }, "name", "GPRSInfoQOSMeanThruClass" },
	{ 201, "attribute", { 0x53 }, "name", "GPRSInfoQOSPeekThruClass" },
	{ 201, "attribute", { 0x54 }, "name", "GPRSInfoQOSReliabilityClass" },
	{ 201, "attribute", { 0x55 }, "name", "GPRSInfoQOSDelayClass" },
	{ 201, "attribute", { 0x56 }, "name", "GPRSInfoQOSPrecedenceClass" },
	{ 201, "attribute", { 0x57 }, "name", "GPRSInfoMinQOSSettingsValid" },
	{ 201, "attribute", { 0x58 }, "name", "GPRSInfoMinQOSMeanThruClass" },
	{ 201, "attribute", { 0x59 }, "name", "GPRSInfoMinQOSPeekThruClass" },
	{ 201, "attribute", { 0x5A }, "name", "GPRSInfoMinQOSReliabilityClass" },
	{ 201, "attribute", { 0x5B }, "name", "GPRSInfoMinQOSDelayClass" },
	{ 201, "attribute", { 0x5C }, "name", "GPRSInfoMinQOSPrecedenceClass" },
	{ 201, "attribute", { 0x5D }, "name", "GPRSInfoParameters" },
	{ 201, "attribute", { 0x5E }, "name", "GPRSInfoHeaderCompress" },
	{ 201, "attribute", { 0x5F }, "name", "GPRSInfoDataCompression" },
	{ 201, "attribute", { 0x60 }, "name", "GPRSInfoAddress" },
	{ 201, "attribute", { 0x61 }, "name", "GPRSInfoAccessPointName" },
	{ 201, "attribute", { 0x62 }, "name", "GPRSInfoL2ProtocolType" },
	{ 201, "attribute", { 0x63 }, "name", "GPRSInfoProtocolType" },
	{ 201, "attribute", { 0x64 }, "name", "RadioLinkInfoResequenceTimer" },
	{ 201, "attribute", { 0x65 }, "name", "RadioLinkInfoRetransmitAttempts" },
	{ 201, "attribute", { 0x66 }, "name", "RadioLinkInfoAckTimer" },
	{ 201, "attribute", { 0x67 }, "name", "RadioLinkInfoMws" },
	{ 201, "attribute", { 0x68 }, "name", "RadioLinkInfolws" },
	{ 201, "attribute", { 0x69 }, "name", "RadioLinkInfoVersion" },
	{ 201, "attribute", { 0x6A }, "name", "RadioLinkInfoValid" },
	{ 201, "attribute", { 0x6B }, "name", "CompressionInfoMaxStringLength" },
	{ 201, "attribute", { 0x6C }, "name", "CompressionInfoMaxDictEntries" },
	{ 201, "attribute", { 0x6D }, "name", "CompressionInfoRequired" },
	{ 201, "attribute", { 0x6E }, "name", "CompressionInfoValid" },
	{ 201, "attribute", { 0x6F }, "name", "CompressionInfoConnectionelement," },
	{ 201, "attribute", { 0x70 }, "name", "FailoverDefault" },
	{ 201, "attribute", { 0x71 }, "name", "FailoverPrompt" },
	{ 201, "attribute", { 0x72 }, "name", "Name" },
	{ 201, "attribute", { 0x73 }, "name", "GPRSInfoHeaderCompression" },

	{ 202, "attribute", { 0x5 }, "type", "BrowserFavorite" },
	{ 202, "attribute", { 0x6 }, "name", "URL" },
	{ 202, "attribute", { 0x20 }, "type", "Sync" },
	{ 202, "attribute", { 0x21 }, "type", "Settings" },
	{ 202, "attribute", { 0x22 }, "type", "Connection" },
	{ 202, "attribute", { 0x23 }, "type", "Mail" },
	{ 202, "attribute", { 0x24 }, "type", "Contacts" },
	{ 202, "attribute", { 0x25 }, "type", "Calendar" },
	{ 202, "attribute", { 0x26 }, "type", "FolderHierarchy" },
	{ 202, "attribute", { 0x2A }, "name", "NotificationsEnabled" },
	{ 202, "attribute", { 0x2B }, "name", "ConflictResolution" },
	{ 202, "attribute", { 0x2C }, "name", "SyncSwitchPurge" },
	{ 202, "attribute", { 0x2D }, "name", "DisconnectWhenDone" },
	{ 202, "attribute", { 0x2E }, "name", "SyncAfterTimeWhenCradled" },
	{ 202, "attribute", { 0x2F }, "name", "BodyTruncation" },
	{ 202, "attribute", { 0x30 }, "name", "AutoSync" },
	{ 202, "attribute", { 0x31 }, "name", "ConflictResolutionHelp" },
	{ 202, "attribute", { 0x32 }, "name", "SyncAfterTime" },
	{ 202, "attribute", { 0x33 }, "name", "AutoSyncWhenCradled" },
	{ 202, "attribute", { 0x34 }, "name", "SavePassword" },
	{ 202, "attribute", { 0x35 }, "name", "User" },
	{ 202, "attribute", { 0x36 }, "name", "Server" },
	{ 202, "attribute", { 0x37 }, "name", "FolderType" },
	{ 202, "attribute", { 0x38 }, "name", "DeviceID" },
	{ 202, "attribute", { 0x39 }, "name", "Device" },
	{ 202, "attribute", { 0x3A }, "name", "URI" },
	{ 202, "attribute", { 0x3B }, "name", "EmailAgeFilter" },
	{ 202, "attribute", { 0x3C }, "name", "SaveSentItems" },
	{ 202, "attribute", { 0x3D }, "name", "MailFileAttachments" },
	{ 202, "attribute", { 0x3E }, "name", "MailBodyTruncation" },
	{ 202, "attribute", { 0x3F }, "name", "CalendarAgeFilter" },
	{ 202, "attribute", { 0x45 }, "name", "SyncEnabled" },
	{ 202, "attribute", { 0x46 }, "name", "VersionMajor" },
	{ 202, "attribute", { 0x47 }, "name", "VersionMinor" },
	{ 202, "attribute", { 0x4A }, "type", "Locale" },
	{ 202, "attribute", { 0x4B }, "name", "LOCALE_INEGCURR" },
	{ 202, "attribute", { 0x4C }, "name", "LOCALE_SMONTHOUSANDSEP" },
	{ 202, "attribute", { 0x4D }, "name", "LOCALE_ICURRDIGITS" },
	{ 202, "attribute", { 0x4E }, "name", "LOCALE_SMONDECIMALSEP" },
	{ 202, "attribute", { 0x4F }, "name", "LOCALE_ICURRENCY" },
	{ 202, "attribute", { 0x51 }, "name", "LOCALE_INEGNUMBER" },
	{ 202, "attribute", { 0x52 }, "name", "LOCALE_STHOUSAND" },
	{ 202, "attribute", { 0x53 }, "name", "LOCALE_IDIGITS" },
	{ 202, "attribute", { 0x54 }, "name", "LOCALE_SDECIMAL" },
	{ 202, "attribute", { 0x58 }, "name", "Language" },
	{ 202, "attribute", { 0x59 }, "name", "Locale" },
	{ 202, "attribute", { 0x60 }, "type", "No-Reply" },
	{ 202, "attribute", { 0x61 }, "type", "Not-Reachable" },
	{ 202, "attribute", { 0x62 }, "type", "Busy" },
	{ 202, "attribute", { 0x63 }, "type", "Unconditional" },
	{ 202, "attribute", { 0x64 }, "name", "TAPI_NETWORK_NUMID_LONGNAME_MAPPING" },
	{ 202, "attribute", { 0x65 }, "name", "TAPI_NETWORK_FORCE_REGISTRATION" },
	{ 202, "attribute", { 0x66 }, "name", "TAPI_NETWORK_PREFERED" },
	{ 202, "attribute", { 0x67 }, "name", "TAPI_NETWORK_SELECT_ CURRENT" },
	{ 202, "attribute", { 0x68 }, "name", "TAPI_NETWORK_CURRENT" },
	{ 202, "attribute", { 0x69 }, "name", "TAPI_NETWORK_ AUTOMATIC" },
	{ 202, "attribute", { 0x6A }, "name", "TAPI_FORWARD_TIMEOUT" },
	{ 202, "attribute", { 0x6B }, "name", "TAPI_FORWARD_ADDRESS" },
	{ 202, "attribute", { 0x6C }, "name", "TAPI_FORWARD_ENABLED" },
	{ 202, "attribute", { 0x6D }, "name", "TAPI_FIXEDDIAL_NUMBERS" },
	{ 202, "attribute", { 0x6E }, "name", "TAPI_FIXEDDIAL_ENABLED" },
	{ 202, "attribute", { 0x6F }, "name", "TAPI_WAITING" },
	{ 202, "attribute", { 0x70 }, "name", "TAPI_SEND_CALLID" },
	{ 202, "attribute", { 0x71 }, "name", "TAPI_BARRING_PASSWORD" },
	{ 202, "attribute", { 0x72 }, "name", "TAPI_PIN2" },
	{ 202, "attribute", { 0x73 }, "name", "SMSC" },
	{ 202, "attribute", { 0x74 }, "name", "Voicemail1" },
	{ 202, "attribute", { 0x75 }, "type", "Tapi" },
	{ 202, "attribute", { 0x76 }, "name", "Voicemail2" },
	{ 202, "attribute", { 0x77 }, "name", "RadioVersion" },
	{ 202, "attribute", { 0x78 }, "name", "CellBroadcastLanguage" },
	{ 202, "attribute", { 0x79 }, "name", "CellBroadcastEnableTopicList" },
	{ 202, "attribute", { 0x7A }, "name", "CellBroadcastEnabled" },
	{ 202, "attribute", { 0x7B }, "name", "TAPI_BARRING_OUT" },
	{ 202, "attribute", { 0x7C }, "name", "TAPI_BARRING_IN" },

	{ 203, "attribute", { 0x5 }, "type", "Home" },
	{ 203, "attribute", { 0x6 }, "type", "HKCU\\ControlPanel\\Home" },
	{ 203, "attribute", { 0x7 }, "name", "DeleteScheme" },
	{ 203, "attribute", { 0x8 }, "name", "BgImage" },
	{ 203, "attribute", { 0x9 }, "name", "ColorScheme" },
	{ 203, "attribute", { 0xA }, "name", "Scheme" },
	{ 203, "attribute", { 0xC }, "type", "Uninstall" },
	{ 203, "attribute", { 0xD }, "type", "uninstall" },
	{ 203, "attribute", { 0x10 }, "type", "Clock" },
	{ 203, "attribute", { 0x11 }, "name", "AlarmTime" },
	{ 203, "attribute", { 0x12 }, "name", "AlarmOn" },
	{ 203, "attribute", { 0x13 }, "name", "Time" },
	{ 203, "attribute", { 0x14 }, "name", "TimeZone" },
	{ 203, "attribute", { 0x15 }, "name", "Date" },
	{ 203, "attribute", { 0x20 }, "type", "EMAIL" },
	{ 203, "attribute", { 0x21 }, "type", "SMTP" },
	{ 203, "attribute", { 0x22 }, "type", "POP3" },
	{ 203, "attribute", { 0x23 }, "type", "IMAP4" },
	{ 203, "attribute", { 0x25 }, "name", "CONNECTIONID" },
	{ 203, "attribute", { 0x26 }, "name", "REPLYADDR" },
	{ 203, "attribute", { 0x27 }, "type", "CertificateStore" },
	{ 203, "attribute", { 0x28 }, "type", "Unprivileged Execution Trust Authorities" },
	{ 203, "attribute", { 0x29 }, "type", "Privileged Execution Trust Authorities" },
	{ 203, "attribute", { 0x2A }, "type", "SPC" },
	{ 203, "attribute", { 0x2B }, "type", "ROOT" },
	{ 203, "attribute", { 0x2C }, "type", "My" },
	{ 203, "attribute", { 0x2D }, "type", "CA" },
	{ 203, "attribute", { 0x2E }, "name", "Role" },
	{ 203, "attribute", { 0x2F }, "name", "EncodedCertificate" },
	{ 203, "attribute", { 0x30 }, "type", "FileOperation" },
	{ 203, "attribute", { 0x31 }, "type", "MakeDir" },
	{ 203, "attribute", { 0x32 }, "type", "RemoveDir" },
	{ 203, "attribute", { 0x33 }, "type", "Shortcut" },
	{ 203, "attribute", { 0x34 }, "type", "Copy" },
	{ 203, "attribute", { 0x35 }, "type", "Move" },
	{ 203, "attribute", { 0x36 }, "type", "Delete" },
	{ 203, "attribute", { 0x37 }, "type", "Extract" },
	{ 203, "attribute", { 0x38 }, "name", "NoOverwriteIfNewer" },
	{ 203, "attribute", { 0x39 }, "name", "NoOverwrite" },
	{ 203, "attribute", { 0x3A }, "name", "ForceDelete" },
	{ 203, "attribute", { 0x3B }, "name", "NoTransaction" },
	{ 203, "attribute", { 0x3C }, "name", "SelfRegister" },
	{ 203, "attribute", { 0x3D }, "name", "Shared" },
	{ 203, "attribute", { 0x3E }, "name", "Source" },
	{ 203, "attribute", { 0x45 }, "type", "Sounds" },
	{ 203, "attribute", { 0x46 }, "type", "HKCU\\ControlPanel\\Sounds\\" },
	{ 203, "attribute", { 0x47 }, "name", "DeleteRingTone" },
	{ 203, "attribute", { 0x48 }, "name", "MessageBox" },
	{ 203, "attribute", { 0x49 }, "name", "Sound" },
	{ 203, "attribute", { 0x4A }, "name", "Mode" },
	{ 203, "attribute", { 0x50 }, "type", "Metabase" },
	{ 203, "attribute", { 0x51 }, "type", "label" },
	{ 203, "attribute", { 0x52 }, "type", "options" },
	{ 203, "attribute", { 0x53 }, "name", "datatype" },
	{ 203, "attribute", { 0x54 }, "name", "maxvalue," },
	{ 203, "attribute", { 0x55 }, "name", "minvalue," },
	{ 203, "attribute", { 0x56 }, "name", "access-role" },
	{ 203, "attribute", { 0x57 }, "name", "rw-access" },
	{ 203, "attribute", { 0x58 }, "name", "semantic-type" },
	{ 203, "attribute", { 0x59 }, "name", "maxlength" },
	{ 203, "attribute", { 0x5A }, "name", "multiple" },
	{ 203, "attribute", { 0x70 }, "name", "Default" },
	{ 203, "attribute", { 0x71 }, "value", "True" },
	{ 203, "attribute", { 0x72 }, "value", "False" },

	{ 204, "attribute", { 0x5 }, "type", "Engines" },
	{ 204, "attribute", { 0x6 }, "type", "Providers" },
	{ 204, "attribute", { 0x7 }, "type", "Sources" },
	{ 204, "attribute", { 0x8 }, "type", "CarrierConnectorList" },
	{ 204, "attribute", { 0x9 }, "name", "AllowSSLOption" },
	{ 204, "attribute", { 0xA }, "name", "CarrierConnector" },
	{ 204, "attribute", { 0xB }, "name", "ClientNegotiated" },
	{ 204, "attribute", { 0xC }, "name", "ClientProtocolVersion" },
	{ 204, "attribute", { 0xD }, "name", "DeviceAddressingMethod" },
	{ 204, "attribute", { 0xE }, "name", "DevicePhoneNumber" },
	{ 204, "attribute", { 0xF }, "name", "DevicePhoneReadOnly" },
	{ 204, "attribute", { 0x10 }, "name", "DeviceSMSAddress" },
	{ 204, "attribute", { 0x11 }, "name", "IncludeRemoteManualSync" },
	{ 204, "attribute", { 0x12 }, "name", "IncludeRemoteSync" },
	{ 204, "attribute", { 0x13 }, "name", "MIMETruncation" },
	{ 204, "attribute", { 0x14 }, "name", "NotificationSupported" },
	{ 204, "attribute", { 0x15 }, "name", "OffPeakFrequency" },
	{ 204, "attribute", { 0x16 }, "name", "OutboundMailDelay" },
	{ 204, "attribute", { 0x17 }, "name", "PeakEndTime" },
	{ 204, "attribute", { 0x18 }, "name", "PeakFrequency" },
	{ 204, "attribute", { 0x19 }, "name", "PeakStartTime" },
	{ 204, "attribute", { 0x1A }, "name", "RadioEnabledDevice" },
	{ 204, "attribute", { 0x1B }, "name", "SendMailItemImmediately" },
	{ 204, "attribute", { 0x1C }, "name", "SyncAfterCount" },
	{ 204, "attribute", { 0x1D }, "name", "SyncWhenRoaming" },
	{ 204, "attribute", { 0x1E }, "name", "Logging" },
	{ 204, "attribute", { 0x1F }, "name", "UseSSL" },
	{ 204, "attribute", { 0x20 }, "name", "ConflictResolutionHelp" },
	{ 204, "attribute", { 0x21 }, "name", "PCurHelp" },
	{ 204, "attribute", { 0x22 }, "name", "PeakDaysLink" },
	{ 204, "attribute", { 0x23 }, "name", "PeakTimesHelp" },
	{ 204, "attribute", { 0x24 }, "name", "ScheduleHelp" },
	{ 204, "attribute", { 0x25 }, "name", "SyncAfterTimeWhenCradledHelp" },
	{ 204, "attribute", { 0x2A }, "type", "CM_WiFiEntries" },
	{ 204, "attribute", { 0x30 }, "type", "Bluetooth" },
	{ 204, "attribute", { 0x31 }, "name", "BtMode" },
	{ 204, "attribute", { 0x32 }, "type", "Obex" },
	{ 204, "attribute", { 0x33 }, "type", "HKLM\\Software\\Microsoft\\Obex" },
	{ 204, "attribute", { 0x34 }, "name", "IsEnabled" },
	{ 204, "attribute", { 0x35 }, "type", "SpeedDial" },
	{ 204, "attribute", { 0x36 }, "name", "Key" },
	{ 204, "attribute", { 0x45 }, "type", "EMAIL2" },
	{ 204, "attribute", { 0x46 }, "type", "NAMEDPROPS" },
	{ 204, "attribute", { 0x47 }, "type", "TAGPROPS" },
	{ 204, "attribute", { 0x48 }, "name", "AUTHREQUIRED" },
	{ 204, "attribute", { 0x49 }, "name", "DWNDAY" },
	{ 204, "attribute", { 0x4A }, "name", "INSERVER" },
	{ 204, "attribute", { 0x4B }, "name", "KEEPMAX" },
	{ 204, "attribute", { 0x4C }, "name", "OUTSERVER" },
	{ 204, "attribute", { 0x4D }, "name", "RETRIEVE" },
	{ 204, "attribute", { 0x4E }, "name", "SERVICENAME" },
	{ 204, "attribute", { 0x4F }, "name", "SERVICETYPE" }
};

struct SWBXMLVersion {
	union {
		struct {
			u_int8 m_uiMinor : 4; /* minor version number */
			u_int8 m_uiMajor : 4; /* major version number - 1 */
		};
	};
};

struct SPublicidInfo {
	std::string m_strName;
	std::string m_strComment;
};

static SPublicidInfo g_msoPublicidInfo[] {
	{ "LITERAL", "String table index follows; public identifier is encoded as a literal in the string table" },
	{ "Unknown or missing public identifier", "" },
	{ "-//WAPFORUM//DTD WML 1.0//EN", "(WML 1.0)" },
	{ "DEPRECATED -//WAPFORUM//DTD WTA 1.0//EN", "(WTA Event 1.0)" },
	{ "-//WAPFORUM//DTD WML 1.1//EN", "(WML 1.1)" },
	{ "-//WAPFORUM//DTD SI 1.0//EN", "(Service Indication 1.0)" },
	{ "-//WAPFORUM//DTD SL 1.0//EN", "(Service Loading 1.0)" },
	{ "-//WAPFORUM//DTD CO 1.0//EN", "(Cache Operation 1.0)" },
	{ "-//WAPFORUM//DTD CHANNEL 1.1//EN", "(Channel 1.1)" },
	{ "-//WAPFORUM//DTD WML 1.2//EN", "(WML 1.2)" },
	{ "-//WAPFORUM//DTD WML 1.3//EN", "(WML 1.3)" },
	{ "-//WAPFORUM//DTD PROV 1.0//EN", "(Provisioning 1.0)" },
	{ "-//WAPFORUM//DTD WTA-WML 1.2//EN", "(WTA-WML 1.2)" },
	{ "-//WAPFORUM//DTD CHANNEL 1.2//EN", "(Channel 1.2)" }
};

struct SWBXMLPublicId {
	union {
		u_int8 m_uiZero;
		mb_u_int32 m_mbPublicId;
	};
};

struct SWBXMLCharset {
	union {
		u_int8 m_uiZero; /* It is strongly recommended that WBXML tokenisers avoid using the charset value "0" */
		mb_u_int32 m_mbCharset; /* If the XML encoding declaration is not present, the character encoding is either UTF-8 or UTF-16 */
	};
};

struct SWBXMLStringtbl {
	mb_u_int32 m_mbLength;
	byte m_mcString[0];
};

#pragma pack(pop)

unsigned long long ub_u_int32_toLongLong (mb_u_int32 &p_mbValue, CFileReader &p_coFileReader, int &p_iResult);
void LongLong_toub_u_int32 (unsigned long long p_ullIn, std::basic_string<mb_u_int32> &p_strOut);

#endif /* _WBXML_H_ */
